"""add auth_provider to users

Revision ID: 05873a71ec24
Revises: 0549296bf3b4
Create Date: 2026-05-05 03:20:18.743944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '05873a71ec24'
down_revision: Union[str, Sequence[str], None] = '0549296bf3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    login_enum = postgresql.ENUM('GOOGLE', 'LOCAL', 'BOTH', name='loginproviderenum')
    login_enum.create(op.get_bind())
    op.add_column('users', sa.Column(
        'auth_provider', 
        sa.Enum('GOOGLE', 'LOCAL', 'BOTH', name='loginproviderenum'), 
        nullable=False, 
        server_default='LOCAL'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    
    # 2. Remove o tipo ENUM do banco
    login_enum = postgresql.ENUM('GOOGLE', 'LOCAL', 'BOTH', name='loginproviderenum')
    login_enum.drop(op.get_bind())
