"""add new columns to stations

Revision ID: b7b90b67800b
Revises: 05873a71ec24
Create Date: 2026-05-16 17:12:11.019825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b90b67800b'
down_revision: Union[str, Sequence[str], None] = '05873a71ec24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('operation_start_date', sa.Date(), nullable=True))
    op.add_column('stations', sa.Column('last_data_date', sa.Date(), nullable=True))
    op.add_column('stations', sa.Column('station_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'station_type')
    op.drop_column('stations', 'last_data_date')
    op.drop_column('stations', 'operation_start_date')
    op.drop_column('stations', 'status')
    # ### end Alembic commands ###
