"""initial schema

Revision ID: c040c245c854
Revises: c04bd8dd75cc
Create Date: 2026-04-07 13:49:01.758434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c040c245c854'
down_revision: Union[str, Sequence[str], None] = 'c04bd8dd75cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('CEMADEN', 'INMET', name='sourceenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('user_type', sa.Enum('ADMIN', 'STUDENT', 'RESEARCHER', 'PROFESSOR', name='usertypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('precipitation_data',
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('filled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('date', 'station_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scenario', sa.Enum('HISTORICAL', 'SSP245', 'SSP585', name='scenarioenum'), nullable=False),
    sa.Column('bias_correction', sa.Enum('NONE', 'QM', 'DBC', 'EQM', name='biascorrectionenum'), nullable=False),
    sa.Column('disaggregation', sa.Enum('NONE', 'CETESB', 'BL', name='disaggregationenum'), nullable=False),
    sa.Column('climbra_file_s3', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idf_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('distribution', sa.Enum('NORMAL', 'LOGNORMAL', 'PARETO', 'GUMBEL_R', 'GEV', 'GENLOGISTIC', name='distributionenum'), nullable=False),
    sa.Column('best_sse', sa.Float(), nullable=False),
    sa.Column('idf_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('DOWNLOAD_STATION_DATA', 'GAP_FILLING', 'QUALITY_ANALYSIS', 'GENERATE_IDF', 'DOWNLOAD_CLIMBRA', 'BIAS_CORRECTION', 'GENERATE_REPORT', name='tasktypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idf_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idf_result_id', sa.UUID(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('return_period', sa.Float(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idf_result_id'], ['idf_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idf_values')
    op.drop_table('jobs')
    op.drop_table('idf_results')
    op.drop_table('projects')
    op.drop_table('precipitation_data')
    op.drop_table('users')
    op.drop_table('stations')
    # ### end Alembic commands ###
